project:
  type: website
  output-dir: docs

book:
  title: "MTH161 :: Fall 2024"
  author: "Chris Hallstrom"
  date: "8/18/2021"
  chapters:
    - index.qmd
    - syllabus.qmd
    - UPElements.qmd

website:
  title: "mth161 :: Elementary Statistics"
  navbar:
    background: "#AAB396"
    right:
      - href: course-links.qmd
        text: Quick Links
  sidebar:
    background: "#F7EED3"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 2

    contents:
      - href: index.qmd
        text: Welcome
      - href: general.qmd
        text: General Info
      - href: support.qmd
      - href: content.qmd
      - href: structure.qmd
      - href: grades.qmd
      - href: UPElements.qmd
        text: University Policies
      - href: course-links.qmd
        text: Useful Links
      - section: "Slides"
        contents:
          - href: slides/05/05-chapter4.qmd
            text: "Tuesday, Week 3"
          - href: slides/06/06-explore-categorical.qmd
            text: "Thursday, Week 3"
          - href: slides/07/07-explore-numerical.qmd
            text: "Tuesday, Week 4"
          - href: slides/08/08-explore-numer-boxplotIQR.qmd
            text: "Thursday, Week 4"
          - href: slides/09/09-linear-regression.qmd
            text: "Tuesday, Week 5"
          - href: slides/10/10-linear-regression.qmd
            text: "Thursday, Week 5" 
          - href: slides/11/11-hypothesis-testing.qmd
            text: "Tuesday, Week 6" 
          - href: slides/12/12-hypothesis-testing.qmd
            text: "Thursday, Week 6" 
          - href: slides/13/13-confidence-intervals.qmd
            text: "Tuesday, Week 7"   
          - href: slides/15/15-inference-mathematical-models.qmd
            text: "Tuesday, Week 8" 
          - href: slides/16/16-inference.qmd
            text: "Thursday, Week 8" 
      - section: "AE"
        contents:
          - href: ae/ae-01/ae-01-penguins.qmd
            text: "AE 01 Meet the Penguins"
          - href: ae/ae-02/ae-02-delta.qmd
            text: "AE 02 COVID"
          - href: ae/ae-03/ae-03-durham.qmd
            text: "AE 03 Durham"
          - href: ae/ae-04/ae-04-flights.qmd
            text: "AE 04 Flights"
          - href: ae/ae-05/ae-05-Finnish-fish.qmd
            text: "AE 05 Finnish Fish"
          - href: ae/ae-06/ae-06-transplants.qmd
            text: "AE 06 Heart Transplants"
          - href: ae/ae-07/ae-07-lemurs.qmd
            text: "AE 07 Lemurs"
format:
  html:
    #theme: cosmo
    theme: simplex
    css: style/mth161.scss
    toc: true

editor: visual

