project:
  type: website
  output-dir: docs

book:
  title: "MTH161 :: Fall 2024"
  author: "Chris Hallstrom"
  date: "8/18/2021"
  chapters:
    - index.qmd
    - syllabus.qmd
    - UPElements.qmd

website:
  title: "mth161 :: Elementary Statistics"
  navbar:
    background: "#AAB396"
    right:
      - href: course-links.qmd
        text: Quick Links
  sidebar:
    background: "#F7EED3"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 2

    contents:
      - href: index.qmd
        text: Welcome
      - href: general.qmd
        text: General Info
      - href: support.qmd
      - href: content.qmd
      - href: structure.qmd
      - href: grades.qmd
      - href: UPElements.qmd
        text: University Policies
      - href: course-links.qmd
        text: Useful Links
      - section: "Slides"
        contents:
          - href: slides/05/05-chapter4.qmd
            text: "Tuesday, Week 3"
          - href: slides/06/06-explore-categorical.qmd
            text: "Thursday, Week 3"
          - href: slides/07/07-explore-numerical.qmd
            text: "Tuesday, Week 4"

      
format:
  html:
    #theme: cosmo
    theme: simplex
    css: style/mth161.scss
    toc: true

editor: visual

