project:
  type: website
  output-dir: docs

website:
  title: "mth161 :: Elementary Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: aboot

  sidebar:
    background: "#DAC0A3"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 1

    contents:
      - href: course-overview.qmd
        text: Overview
      - href: syllabus.qmd
      - section: "Course information"
      - section: "Slides"
        contents:
          - href: slides/01/01-welcome.qmd
            text: 01 Welcome
          - href: slides/02/02-hello-data.qmd
            text: 02 Hello Data
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

