project:
  type: website
  output-dir: docs

website:
  title: "mth161 :: Elementary Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: aboot

  sidebar:
    background: "#798b93"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 1

    contents:
      - href: course-overview.qmd
        text: Overview
      - href: syllabus.qmd
      - section: "Course information"
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

