---
title: "Class Structure"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

## Attendance and Engagement

To get the most out of this course, you should be present and actively engaged in class. There are many ways to be engaged: regularly attending class, completing pre-class and other assignments on-time, engaging productively in group work, asking questions, supporting your classmates, coming to student support hours, and more. To help you develop a habit of engagment, you will have a weekly opportunity to reflect on how you're engaging in our class.

While I do expect you to be in class, I also recognize that occasionally things come up that might prevent you from being there. If you do miss class, you can always check our class Moodle page to see what we covered that day. If you find yourself missing class more than a few times, you can expect that I will check with you to see how I can support your attendence better.

## Homework

Much of our class time will be devoted to working together on activities designed to build understanding on concepts introduced in the textbook. To help ensure that you're prepared for class, I will assign short daily homework (typically 2-3 problems from the book). You should plan on coming to class prepared to discuss this work with your classmates.

## Application Exercises (AE)

These are in-class activities that we will work on in groups. They are designed to introduce or reinforce specfic concepts as well as introduce chunks of R code that we'll use for visualization and data analysis. If you have a laptop or tablet, you may find it helpful to bring it to class but as long as someone at your table has a device, that will be sufficient.

## Interactive R tutorials

Each chapter in our book includes a number of interactive tutorials to help you learn how to use R for data visualization and analysis. While these are not required, they are highly recommended for gaining proficiency in using R. You can include this work in your weekly report.

## Weekly Report

Each week, I will ask you to complete a short one-page reflection on that week's engagment. Your report should include the following information:

-   How did you engage in the class this week? Did you attend class? Were you on-time? Did you attend student support hours?
-   Did you complete the assigned homework problems? Did you find them helpful?\
-   What questions came up for you have while doing these problems or doing the class activities? How did you resolve these questions? What questions do you still have?
-   In what ways were you able to help support the learning of your classmates?

## Labs

Approximately every two weeks, I will assign a lab. You can think of these as extended homework assignments that will combine concepts with practice. You will use RStudio (posit.cloud) to complete a lab report which you'll submit on Moodle. I will provide feedback after which you're welcome to resubmit any work within one week.

## Quizzes and Exams

We will have occasional short in-class quizzes which will serve as a mechanism for both you an me to check-in about where you are with your understanding of the material. Whether or not you include these check-ins in your portfolio as evidence of your understanding is up to you.

We will not have traditional midterm or final exams.

## Portfolio

You are encouraged to use the portfolio template in our posit.cloud space to keep track of your learning over the course of the semester. Think of this as your course scrapbook to which you can add any homework, activities, or other evidence of your learning.

## Projects

There are two projects in this course - the first one is due mid-semester and the second one is due at the end of the semester.
