---
title: "MTH161 :: Elementary Statistics <br> Fall 2024"
subtitle: "Sections H, I"
format:
  html: 
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

::: center
# Welcome! {.unnumbered}
:::

I am looking forward to working with each of you this semester! It is my top priority to support your growth as a learner and to make our time together both in class and out productive and engaging. I will strive to create an learning environment where all of our different perspectives and identities are valued and respected, where the contributions of every person are celebrated, and where you feel comfortable fully engaging in class.

While I'll do everything in my power to support you, your success in this course ultimately depends on you. I ask you to bring a readiness to work and a belief that you can learn. **I absolutely believe this about each of you**. I will also ask you to do tasks that are just at the edge of what you can handle because that is how the best learning happens, but if you are prepared to invest your time and energy, and to communicate with me about how you're doing, I can and will support you.

As we work together this semester, your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups. In particular, if you ever feel like your experience in this class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the class, your academic deans are an excellent resource.
