{
  "hash": "d0c39036f09664a879bb9c02d28cf2f7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Inference for Two Proportions\nsubtitle: Chapter 17\nauthor: \"\"\nformat: revealjs\nauto-stretch: false\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n## CPR + blood thinner survival rates\n\n> Patients who received CPR (cardiopulmonary resuscitation) after a heart attack were randomly divided into two groups. The **treatment** group was given a blood thinner, the **control** group was given none. Did the blood thinner meaningfully impact survival rates (over 24 hours)?\n\n\\ \n \nCan we use a normal distribution to model this situation? We must check CLT conditions for [both groups]{.red}: treatment and control.\n\n## CPR + blood thinner survival rates\n\n![](images/cprtable.png){width=\"100%\"} \n\n\n- Independence?  Patients assigned randomly. $\\checkmark$\n- Success/failure condition? In [both groups]{.red} (treatment and control) we see at least 10 successes (e.g. survival) and 10 failures. $\\checkmark$\n\n## CPR confidence interval\n\n![](images/cprtable.png){width=\"70%\"}\n\nBuild a 95% confidence interval for the survival rate difference between these two groups.\n\n$$\n\\hat{p}_T - \\hat{p}_C = \\frac{14}{40} - \\frac{11}{50} = .35 - .22 = .13\n$$\nWhat does it mean that the difference in proportions is [positive]{.red}?\n\n## CPR confidence interval\n\n[NEW!]{.red} Standard error calculation now also involves [both groups]{.red}: \n$$\n\\begin{align}\nSE &= \\sqrt{ \\frac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}  }\\\\\n{~~~~~~~} &= \\sqrt{ \\frac{.35(1-.35)}{40} + \\frac{.22(1-.22)}{50}  } \\\\\n &= .095496\n \\end{align}\n$$\n\n## Building the confidence interval\n\nWe found $\\hat{p}_T - \\hat{p}_C = .13$ and SE = .095\n\n\\\n$$\n\\begin{align}\n\\textrm{CI} &= \\textrm{point estimate} \\pm \\textrm{margin of error}\\\\\n&= \\textrm{point estimate} \\pm \\, z^* \\cdot SE \\\\\n&= .13 \\pm 1.96(.095) \\\\\n&= .13 \\pm .1862 \\\\\n&= (-.0562, .3162)\n\\end{align}\n$$\nWhere did this $z^*$ come from?  \nInterpret what this interval tells us.\n\n## Visualizing the confidence interval\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopenintro::normTail(m=.13, s=.095, M= c(-.056, .316))\n```\n\n::: {.cell-output-display}\n![](21-Chapter17_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n\n## Fish Oil Benefits\n> A five-year experiment was conducted to evaluate the effectiveness of n-3 fatty acid supplements (fish oils) on reducing heart attacks.\n\n\n|  | heart attack | no event | Total |\n|------|------|------|------|\n| fish oil    | 145      | 12788      | 12933      |\n| placebo     | 200      | 12738      | 12938      |\n\n\n## Test statistic\n\nWe're interested in the [difference of two proportions]{.red}\n\n$$\\hat{p}_{1} = \\frac{145}{12933} = 0.0112$$\n$$\\hat{p}_{2} = \\frac{200}{12938} = 0.0155$$\n$$ \n\\hat{p}_{1} - \\hat{p}_{2} = 0.0112-0.0155 = -0.0043\n$$\nIs this observed difference significant?  Or is it the result of random variation?\n\n## Hypothesis Test\n\n- Null hypothesis:  there is no difference between the two groups\n$$\nH_0:  p_1 - p_2 = 0\n$$\n\n- Alternative hypothesis:  patients that took the fish oil supplement had a reduced rate of heart attack\n$$\nH_A:  p_1 - p_2 < 0\n$$\n- [Special case]{.red}: when $H_0$ is that the proportions are **equal**, we use a [pooled proportion]{.red} to check conditions and find SE.\n\n\n## Verify conditions for the model\n\n- Independent?  Yes, this was a randomized study\n\n- Large enough sample size?  Use [pooled proportion]{.red}.\n\n$$\n\\begin{align}\n\\hat{p}_{\\mbox{pool}} = \\frac{ \\mbox{number of successes}}{\\mbox{number of cases}}\n&=\\frac{\\hat{p}_1 n_1 + \\hat{p}_2 n_2}{n_1 + n_2}\\\\\n&= \\frac{145 + 200}{25871}\n\\end{align}\n$$\n\n$$\n\\hat{p}_{\\mbox{pool}} = 0.0133\n$$\n\n\n## Sample Size, continued\n\nUse pooled proportion $\\hat{p}_\\mbox{pool}$ written simply as $\\hat{p}$\n\n- $n_1 \\hat{p} \\geq 10$ and $n_1 (1 - \\hat{p}) \\geq 10$\n- $n_2 \\hat{p} \\geq 10$ and $n_2 (1 - \\hat{p}) \\geq 10$\n\nIn this example,\n\n- $12933 * 0.0133 = 172$\n- $12933 * (1-0.0133)$\n- $12938 * 0.0133$\n- $12938 * (1-0.0133)$\n\n## Standard Error and Z-score\n\nFor difference of two proportions, we use our [new formula]{.red} with the pooled proportion for both groups\n\n$$\nSE = \\sqrt{ \\frac{\\hat{p}_1(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2(1-\\hat{p}_2)}{n_2}  }\\\\\n= \\sqrt{ \\hat{p}(1- \\hat{p}) \\left ( \\frac{1}{n_1} + \\frac{1}{n_2} \\right ) }\n$$\n$$\n\\begin{align}\nSE &=\n\\sqrt{ 0.0133(1-0.0133)\\left ( \\frac{1}{12933} + \\frac{1}{12938} \\right )} \\\\\n&= 0.0014\n\\end{align}\n$$\n\n\n\n## Calculate Z-score\n\n$$\n\\begin{align}\nZ = \\frac{ (\\hat{p}_1 - \\hat{p}_2)}{ SE} &= \\frac{ (\\hat{p}_1 - \\hat{p}_2)}{ \\sqrt{ \\hat{p}(1- \\hat{p}) \\left ( \\frac{1}{n_1} + \\frac{1}{n_2} \\right ) }} \\\\\n&= \\frac{ -0.0043}{0.0014} \\\\\n&= -3.071\n\\end{align}\n$$\n\n## p-value\n\nHow unlikely is it to observe a Z-score of -3.071, or more extreme?\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](21-Chapter17_files/figure-revealjs/unnamed-chunk-2-1.png){width=60%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(-3.07)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.001070294\n```\n\n\n:::\n:::\n\n\n\n## Conclusion\n\nSince the p-value of 0.001 is less than discernment level $\\alpha = 0.05$, we conclude that we have evidence to reject the null hypothesis.  It appears that the observed difference is significant suggesting that fish oil supplements do decrease incidents of heart attacks.\n\n\n\n\n::: {.cell}\n<style type=\"text/css\">\n.red {\ncolor: #B8001F;\n}\n</style>\n:::\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "21-Chapter17_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}