{
  "hash": "28b59c700c7b5d1d11149503cf1b9bc5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Linear Regression, Cont.\nsubtitle: Chapter 7\nformat: revealjs\nauto-stretch: false\nauthor: \"\"\n---\n\n::: {.cell}\n\n:::\n\n\n\n## In groups\n\n-   Discuss Homework: \\S 7.5 #7, 21, 30, 31\n\n## Goals\n\n-   Interpreting $r$ (correlation coefficient)\n-   Interpreting linear model\n\n## Correlation Coefficient\n\n::: {.callout-note icon=\"false\" appearance=\"simple\"}\nA number between -1 and 1 which describes the strength and direction of a **linear** relationship. Denoted $r$\n:::\n\n![](../images/correlations.png){fig-align=\"center\" width=\"90%\"}\n\n## What do these datasets all have in common?\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-linear-regression_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n\n::: fragment\nThe all have roughly the same correlation $r = -0.06$\n\nCorrelation is only meaningful for **linear** assocations\n:::\n\n## Strength of Fit\n\nCorrelation $r$ describes strength and direction of linear relationships\n\nmore commonly use $r^2$ -- which is usually capitalized $R^2$.\n\n\\\n\n> $R^2$ measures the amount of variation in outcome variable that's explained by the linear model.\n\n## $R^2$ Example\n\nFor our cricket chirps we found $r=0.825$\n\nso $R^2 = (0.825)^2 = 0.681$.\n\n> This means that $0.681$ or $68.1$% of the variation we see in cricket chirp rates can be explained by the ambient temperature. What might account for the other $31.9$% of the variation in chirps?\n\n## `crickets` {visibility=\"hidden\"}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Linear Regression\n\n$$ \\hat{y} = b_0 + b_1 \\cdot \\hat{x} $$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-linear-regression_files/figure-revealjs/unnamed-chunk-5-1.png){width=90%}\n:::\n:::\n\n\n\n## A Shortcut!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n model_fit <- linear_reg() |>\n      fit(chirps_in_15s ~ temp_F, data = crickets)\n \ntidy(model_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   -0.372    3.23      -0.115 0.910   \n2 temp_F         0.212    0.0402     5.27  0.000151\n```\n\n\n:::\n:::\n\n\n\n$$ \\hat{y} = -0.372 + 0.212 \\, \\hat{x} $$\n\n## Don't Extrapolate!!\n\n$$ \\hat{y} = -0.372 + 0.212 \\, \\hat{x} $$\n\nWhat do you expect the chirp rate will be if temperature is 100?\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-linear-regression_files/figure-revealjs/unnamed-chunk-7-1.png){width=80%}\n:::\n:::\n\n\n\n## Interpreting the slope\n\n$$ \\hat{y} = -0.372 + 0.212 \\, \\hat{x} $$\n\nSlope of $0.212$ means that for every increase of 1 degree (F), the chirp rate will increase by 0.212.\n\n## Outliers\n\nEach data set has at least one outlier. How do the outliers affect the slope of the regression line?\n\n![](10images/residuals_outlier.png){fig-align=\"center\" width=\"90%\"}\n\n## Practice for next time\n\nSection 11.5 #1, 3\n\n\\\n\nNow head to Posit Cloud for [AE05 - Finnish Fish](https://posit.cloud/spaces/519774/content/8841417)!\n",
    "supporting": [
      "10-linear-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}