{
  "hash": "527c79dd6b870cc3f793de0bf8fade5a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Linear Regression\nsubtitle: Chp 7\nformat: revealjs\nauto-stretch: false\n---\n\n::: {.cell}\n\n:::\n\n\n\n## In groups\n\n-   Practice from last time: \\S 7.5 (3, 7, 9, 19)\n\\\n\n- Practice for next time: \\S 7.5 ()\n\n\n## Associations between two numerical variables\n\n- Explanatory variable: $x$, independent \n(a variable you think might be related to response )\n- Response variable: $y$, dependent \n(a variable you want to understand)\n\n![](09images/grid.png){fig-align=\"center\" width=\"300\"}\n\n\n## Data: `possum`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(possum)\n\nglimpse(possum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 104\nColumns: 8\n$ site    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ pop     <fct> Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vic, Vi…\n$ sex     <fct> m, f, f, f, f, f, m, f, f, f, f, f, m, m, m, m, f, m, f, f, f, m, f, m, …\n$ age     <int> 8, 6, 6, 6, 2, 1, 2, 6, 9, 6, 9, 5, 5, 3, 5, 4, 1, 2, 5, 4, 3, 3, 4, 2, …\n$ head_l  <dbl> 94.1, 92.5, 94.0, 93.2, 91.5, 93.1, 95.3, 94.8, 93.4, 91.8, 93.3, 94.9, …\n$ skull_w <dbl> 60.4, 57.6, 60.0, 57.1, 56.3, 54.8, 58.2, 57.6, 56.3, 58.0, 57.2, 55.6, …\n$ total_l <dbl> 89.0, 91.5, 95.5, 92.0, 85.5, 90.5, 89.5, 91.0, 91.5, 89.5, 89.5, 92.0, …\n$ tail_l  <dbl> 36.0, 36.5, 39.0, 38.0, 36.0, 35.5, 36.0, 37.0, 37.0, 37.5, 39.0, 35.5, …\n```\n\n\n:::\n:::\n\n\n\n\n## Possums: `tail_l' vs 'total_l' \n\nDo possums' tail length and total body length seem to be associated?  Might knowing one help us predict the other?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = possum, aes(y = total_l, x = tail_l)) +\n  geom_point() +\n   labs(x = \"Length of Possum Tail (cm)\",\n       y = \"Length of Possum Body (cm)\")\n```\n\n::: {.cell-output-display}\n![](09-linear-regression_v_files/figure-html/unnamed-chunk-3-1.png){width=90%}\n:::\n:::\n\n\n\n\n## Linear model: \"line of best fit\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = possum, aes(y = total_l, x = tail_l)) +\n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](09-linear-regression_v_files/figure-html/unnamed-chunk-4-1.png){width=80%}\n:::\n:::\n\n\n\n\n## Finding the \"least squares\" regression line\n\nRecall: a line has the equation\n$$ y=mx+b$$\nwhere $m$ = slope and $b$ = $y$-intercept.  Here, we want a line of the form\n\n$$ \\textrm{Total body length} = b_0 + b_1 \\cdot \\textrm{(Tail length)} $$\n\nHow could you use this line to predict the total body length of a possum with tail 41.6 cm long?\n\n\n\n## Properties\n\nThe **least squares regression line** has the following properties:\n\n- Minimizes (sum of squared) distance between data points and line\n- The *residuals* balance out above and below line\n- The point $(\\bar{x}, \\bar{y})$ always lies on line (though it's not necessarily a data point!)\n\n\n## Correlation coefficient, *r*\n\nAlso called the Pearson Product-Moment Correlation, here's how *r* is calculated:\n$$ r(x,y) = \\frac{\\sum_{i=1}^{n} (x_i-\\bar{x})(y_i-\\bar{y})}{\\sqrt{\\sum_{i=1}^{n}(x_i-\\bar{x})^2 \\cdot\\sum_{i=1}^{n}(y_i-\\bar{y})^2 }}$$\nThis is a good computation to have R do for us!\n\n## Correlation coefficient, *r*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npossum |>\n  summarize(N = n(), \n      r = cor(tail_l, total_l, \n              use = \"pairwise.complete.obs\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n      N     r\n  <int> <dbl>\n1   104 0.566\n```\n\n\n:::\n:::\n\n\n\nWhat does this number mean?\n\n\n## Visualizing the correlation coefficient, *r*\n\n![](09images/correlation.png){fig-align=\"center\" width=\"400\"}\n\nWhat would a correlation of $r = -0.998$ look like?  How about $r=1$?\n\n\n## Finding the \"least squares\" regression line\n\n$$ y = b_0 + b_1 \\cdot x $$\nFirst we find the slope: $$b_1 = r \\left( \\frac{s_y}{s_x} \\right)$$\n\nwhere: \n\n- $r$ = correlation coefficient\n- $s_y$ = standard deviation of $y$\n- $s_x$ = standard deviation of $x$\n\nNext we use the fact that $(\\bar{x}, \\bar{y})$ lies on our line to solve for the intercept, $b_0$: \n\n$$\\bar{y} = b_0 + b_1 \\cdot \\bar{x} $$\n\n\n\n## Example (continued)\n\nTo model the association between `tail_l` and `total_l`, we need summary statistics to find the slope and intercept of the linear regression:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npossum |>\n  summarize( \n    mean_x = mean(tail_l),\n    sd_x = sd(tail_l),\n    mean_y = mean(total_l),\n    sd_y = sd(total_l),\n    r = cor(tail_l, total_l)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  mean_x  sd_x mean_y  sd_y     r\n   <dbl> <dbl>  <dbl> <dbl> <dbl>\n1   37.0  1.96   87.1  4.31 0.566\n```\n\n\n:::\n:::\n\n\n\nWhat line does this produce?\n\n\n## Example: `Possum` regression line\n\nFirst, find the slope: \n\n$$\nb_1 = r \\cdot \\left( \\frac{s_y}{s_x} \\right) = .566 \\left( \\frac{4.31}{1.96} \\right) = 1.24\n$$\nNext, use $(\\bar{x}, \\bar{y})$ to find the intercept:\n$$\n\\bar{y} = b_0 + b_1 \\cdot \\bar{x}  \\quad \\implies \\quad 87.1 = b_0 + 1.24(37.0)  \n$$\n\n$$\n\\implies  b_0 = 87.1 - 1.24 (37.0) = 41.2\n$$ \n\nThus: $y = 41.2 + 1.24 x$ is the linear model describing these two possum variables.\n\n## Example: `Possum` regression line\n\n$$\ny = 41.2 + 1.24 x\n$$\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](09-linear-regression_v_files/figure-html/unnamed-chunk-7-1.png){width=90%}\n:::\n:::\n\n\n\n\n## Example: `Possum` regression line\n\nAlternately, we can find the entire **linear model** in one go:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n model_fit <- linear_reg() |>\n      fit(total_l ~ tail_l, data = possum)\n \ntidy(model_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    41.0      6.66       6.16 1.43e- 8\n2 tail_l          1.24     0.180      6.93 3.94e-10\n```\n\n\n:::\n:::\n\n\n\n- What does the intercept (41) mean?  \n- What does the slope (1.24) tell us?\n\n\n## Practice\n\n\n",
    "supporting": [
      "09-linear-regression_v_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}