---
title: Welcome to MTH 161
subtitle: Sections H/I <br>Fall 2024
format: revealjs
---

# Course Details

## Instructor {.smaller}

::: columns
::: {.column width="50%"}
Prof. Chris Hallstrom

BC 270

[hallstro\@up.edu](mailto:hallstro@up.edu)
:::
:::

# Let's play a game!

::: task
-   Form a small group (2-4 people) with people sitting around you

-   First, introduce yourselves to each other -- name (and proper pronunciation of name), year, major, where are you from, etc.

-   Play the game: <https://nyti.ms/3suUJHG>
:::

## Hello data

### Application exercise: UN Votes

::: task
Go to Posit Cloud and start the project called UN Votes. Render the document titled `unvotes.qmd`. Review the narrative and the data visualization you just created.

Take turns changing "Turkey" to another country of your choice and re-render the document. With your group, discuss:

1.  why you chose that country

2.  how this new visualization is different than the original (and what that says about country politics, if anything).

Time permitting: How were these data collected?
:::
