{
  "hash": "9476c56565130b2c86205ec48a52c572",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Hypothesis Testing\nsubtitle: Chapter 11\nformat: revealjs\nauto-stretch: false\nauthor: \"\"\n---\n\n::: {.cell}\n\n:::\n\n\n## In groups\n\n-   Discuss Homework: Chapter 11, #1, 2\n\n## Remember the Penguins!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, mapping = aes(x = body_mass_g)) +\n  geom_histogram(binwidth=200, col=\"white\", fill = \"seagreen\")\n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Density plot (new)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, mapping = aes(x = body_mass_g)) +\n  geom_density(fill = \"seagreen\")\n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Box plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, mapping = aes(x = body_mass_g)) +\n  geom_boxplot(fill = \"seagreen\")\n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Body mass *faceted* by `species`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(penguins, mapping = aes(x = body_mass_g)) +\n  geom_histogram(binwidth=200, col=\"white\", fill = \"seagreen\") +\n  facet_wrap(~species)\n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Mulitple boxplots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, mapping = aes(x = body_mass_g, fill = species)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## Overlay density plots (new!)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, mapping = aes(x = body_mass_g, fill = species)) +\n  geom_density(alpha = 0.3)\n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Ridge plot (new!)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = body_mass_g, y = species, fill = species)) +\n  geom_density_ridges(alpha = 0.3) \n```\n\n::: {.cell-output-display}\n![](11-hypothesis-testing_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n## Summary Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(species) |>\n  summarize( mean = mean(body_mass_g, na.rm = TRUE),\n             sd = sd(body_mass_g, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  species    mean    sd\n  <fct>     <dbl> <dbl>\n1 Adelie    3701.  459.\n2 Chinstrap 3733.  384.\n3 Gentoo    5076.  504.\n```\n\n\n:::\n:::\n\n\n\\\n\n**Question:** Are the mean body weights of Adelie and Chinstraps *really* different? Or is the difference just due to random *variation*?\n\n## Sample vs Population\n\n-   Chapter 5: sample mean is (hopefully) an approxmiation of the population mean\n\n-   Clearly the **sample means** are different (3701 vs. 3733)\n\n-   But are the **population means** different?\n\n::: fragment\n### What do you think?\n:::\n\n## Hypothesis Testing\n\n-   $H_0$ -- Null Hypothesis (no difference)\n\nMean body weight of Adelie and Chinstrap penguins are the same.\n\n-   $H_1$ -- Alternative Hypothesis (there is a difference)\n\nMean body weight of Adelie and Chinstrap penguins are different.\n\n## Coin Flipping\n\nIf you flip a fair coin 100 times, how many times will it come up **heads**?\n\n[Do a simulation](https://www.rossmanchance.com/applets/2021/oneprop/OneProp.htm)\n\n## Gender Discrimination Study\n\nTextbook [Section 11.1](https://openintro-ims.netlify.app/foundations-randomization#sec-caseStudySexDiscrimination)\n",
    "supporting": [
      "11-hypothesis-testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}